### ISSUE TITLE
Problem rendering with leafmap.Map() + lonboard

### ISSUE THREAD

**Issue by ncclementi** [opengeos/leafmap#699] opened 2024-03-04 17:21 UTC
In this blog that I wrote https://ibis-project.org/posts/ibis-duckdb-geospatial/

I'm doing 

```python
import leafmap.deckgl as leafmap

m = leafmap.Map()

m.add_vector(broad_station_gdf, get_fill_color="blue")
m.add_vector(sts_near_broad_gdf, get_color="red", opacity=0.5)
m.add_vector(streets_gdf, get_color="grey", zoom_to_layer=False, opacity=0.3)
m
```

and I the plot doesn't render correctly, and I get this error 
```
'pyarrow.lib.Table' object has no attribute '_bbox'
'pyarrow.lib.Table' object has no attribute '_bbox'
```

This used to work before, it's not clear what's happening. 

### Environment Information

-  leafmap version:  `leafmap  0.31.2  pyhd8ed1ab_0    conda-forge`
-  lonboard version: `lonboard   0.6.0    pypi_0    pypi`
-  Python version: `3.11.8`
-  Operating System: MacOS Sonoma 14.3.1

**Comment by giswqs** [comment] 2024-03-04 17:31
I believe the issue has been resolved in #693. Will be releasing a new version shortly.

**Comment by giswqs** [comment] 2024-03-04 17:34
v0.31.4 has been released. Try `pip install -U leafmap`. The conda-forge package might be available in a few hours.

**Comment by giswqs** [comment] 2024-03-04 17:36
It is an upstream issue. See https://github.com/developmentseed/lonboard/issues/365

**Comment by ncclementi** [comment] 2024-03-04 17:42
I don't get the error but it doesn't render anything. I saw the upstream issue, but they are saying it's because it's using a private method and they close it, so not sure what's going on. 

I'll do a clean install and check again.

**Comment by ncclementi** [comment] 2024-03-04 17:55
This is what I get when I run the same code now. 

<img width="1145" alt="Screenshot 2024-03-04 at 10 55 15 AM" src="https://github.com/opengeos/leafmap/assets/7526622/acd6bda5-ee0c-4ecb-b1da-9f8aa9fac023">

**Comment by ncclementi** [comment] 2024-03-04 18:19
For the record 

```python
m = leafmap.Map()
m
```
renders the world map, but as soon as I try to do `m.add_vector(...)` the rendering turns out empty

**Comment by ncclementi** [comment] 2024-03-04 18:27
In fact, if I try to run the similar examples from your notebooks here https://leafmap.org/notebooks/83_vector_viz/ in colab, after installing lonboard. 

If you add the rendering of `m` in any of the cells that add something like : 

```python
streets = gpd.read_file("nyc_streets.shp")
m.add_gdf(streets, zoom_to_layer=True, pickable=True, get_width=5)
m
```

or 
```python
m.add_vector("nyc_subway_stations.shp", get_radius=10, get_fill_color=[255, 0, 0, 180])
m
```

You will see that it doesn't render.

**Comment by giswqs** [comment] 2024-03-04 18:37
The recent lonboard updates might caused this. I will look into it.

**Comment by ncclementi** [comment] 2024-03-04 20:54
Just for the record: I tried downgrading to `lonboard==0.5.0` but didn't work either :/

**Comment by giswqs** [comment] 2024-03-04 20:55
I already identified the root cause of the issue. Will be fixing it later today.

**Comment by ncclementi** [comment] 2024-03-04 20:56
Thank you @giswqs 🙌

**Closed** 2024-03-05 04:41 UTC
Labels: bug
